server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eco_manager?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

api:
  prefix: api/v1

jwt:
  expiration: 2592000 #30 days
  secretKey: zIvlQSI0zOCDewEMsLkq1gVEgss5bl8B5zBV+MBDiwQ=

logging:
  level:
    org:
      springframework:
        web=DEBUG:
        security=DEBUG: